before_install:
- sudo systemsetup -settimezone Europe/Zaporozhye

language: objective-c

script:
- xcodebuild build -project cocoa/PubNubMacOSTestApplication/PubNubMacOSTestApplication.xcodeproj  > ./coverage/log_Mac.txt
- xcodebuild build -project iOS/iPadDemoApp/pubnub.xcodeproj -sdk iphonesimulator ARCHS=i386 ONLY_ACTIVE_ARCH=YES VALID_ARCHS=i386  > ./coverage/log_iOS.txt


env:
  global:
    secure: A8/KQlKn1BqiutopWcmIg8eh3YeBlIiO6xeDE36QFyyEBiMeeUWd5daXH+2azU0IraBIxxg7TcmKoBnKgtyrzQiAQqGH703PMdzILKercSGIfVcuAiJ6fIWF94v7HfP0wrKzrvwuLSwKK0CP4gv56/lv/f/aIw1Las1L99fFuOk=


after_success: ./update-gh-pages.sh

