notifications:
  email:
    recipients:
      - tullerVal@gmail.com
      - tuller@bk.ru
    on_success: always
    on_failure: always	

before_install:
- sudo systemsetup -settimezone Europe/Zaporozhye
- mkdir ./coverage
- cd .bin/
- ./copyLibs.sh
- cd ..


language: objective-c


script:
- if xcodebuild build -project cocoa/PubNubMacOSTestApplication/PubNubMacOSTestApplication.xcodeproj  > ./coverage/log_Mac.txt; then echo "success"; rm ./coverage/log_Mac.txt; else echo "fail"; fi

- if xcodebuild build -project iOS/iPadDemoApp/pubnub.xcodeproj -sdk iphonesimulator ARCHS=i386 ONLY_ACTIVE_ARCH=YES VALID_ARCHS=i386  > ./coverage/log_iOS.txt; then echo "success"; rm ./coverage/log_iOS.txt; else echo "fail"; fi

 - if xcodebuild test -project iOS/tests/iOSUnitTests/pubnub.xcodeproj -scheme unitTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -configuration Debug > ./coverage/log_Test_unitTest.txt; then echo "success"; rm ./coverage/log_Test_unitTest.txt; rm ./coverage/log_Test_unitTest.txt; else echo "fail"; fi

# - if xcodebuild test -project iOS/tests/iOSUnitTests/pubnub.xcodeproj -scheme travis-ci -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -configuration Debug > ./coverage/log_Test_iOS.txt; then echo "success"; rm ./coverage/log_Test_iOS.txt; rm ./coverage/log_Test_iOS.txt; else echo "fail"; fi

after_failure:
- echo "fail" > ./coverage/fail.txt

after_success:
- rm ./coverage/fail.txt

after_script:
- ./update-gh-pages.sh

