before_install:
- sudo systemsetup -settimezone Europe/Zaporozhye

language: objective-c

script:
- xcodebuild build -project cocoa/PubNubMacOSTestApplication/PubNubMacOSTestApplication.xcodeproj  > ./coverage/log_Mac.txt
- xcodebuild build -project iOS/iPadDemoApp/pubnub.xcodeproj -sdk iphonesimulator ARCHS=i386 ONLY_ACTIVE_ARCH=YES VALID_ARCHS=i386  > ./coverage/log_iOS.txt


env:
  global:
 - secure: A8/KQlKn1BqiutopWcmIg8eh3YeBlIiO6xeDE36QFyyEBiMeeUWd5daXH+2azU0IraBIxxg7TcmKoBnKgtyrzQiAQqGH703PMdzILKercSGIfVcuAiJ6fIWF94v7HfP0wrKzrvwuLSwKK0CP4gv56/lv/f/aIw1Las1L99fFuOk=
  - secure: cUOMlvKFAWpk2yCcKI5R0YwQ1AHvf7dQueKbT+kpqarLQdIkeXk84VAu6XY0Vx4kpc43XcnOCwu0JiiXY5fBfo5RWP2ZTPeFTs284d3mQMnFnulotNBy+88RYAIdIecn6zrV4OS3ScjvPfM07eeDBhqRLvNqXoZobbbuN+7tJGs=


# after_script: ./update-gh-pages.sh


after_script:
- echo -e "Starting to update gh-pages\n"
- cp -R coverage $HOME/coverage

- cd $HOME
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "TullerVal"

# - git clone --branch=gh-pages https://${GH_TOKEN}@github.com/TullerVal/SharedTravisLogs.git gh-pages
- git clone --branch=gh-pages https://cf75effcf9d0ba6e5fdb3d7d6158f1a8e4054e7e@github.com/TullerVal/SharedTravisLogs.git gh-pages

- cd gh-pages
- cp -Rf $HOME/coverage/* .

#add, commit and push files
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
- git push -fq origin gh-pages

- echo -e "Done magic with coverage\n"
